[package]
name = "lyr"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "^0.26.1"
tui = { package = "ratatui", version = "^0.20.1" }
toml = "^0.7.3"
serde = { version = "^1.0.160", features = ["derive"] }
editable-word = { path = "./editable-word" }
pam = "^0.7.0"
anyhow = "^1.0.40"
